version: "3.9"

services:
  bot:
    container_name: bot
    build: .
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    restart: on-failure
    depends_on:
      - redis
    volumes:
      - "./:/app"
      - "/app/node_modules/"

  redis:
    image: redis:6
    ports:
      - 6379:6379
    volumes:
      - ./redis-volume:/data
